=== ElAmriMehdi/Test-avec-Junit4/Tp2/RationnelSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.org/RationnelSchema" xmlns:tns="http://www.example.org/RationnelSchema" elementFormDefault="qualified">

    <complexType name="Rationnel">
    	<attribute name="numerateur" type="int"></attribute>
    	<attribute name="denominateur" type="int"></attribute>
    </complexType>
    

    <complexType name="Data">
    	<sequence>
    		<element name="r1" type="tns:Rationnel"></element>
    		<element name="r2" type="tns:Rationnel"></element>
    		<element name="resultAddition" type="tns:Rationnel"></element>
    		<element name="resultSoustraction" type="tns:Rationnel"></element>
    	</sequence>
    </complexType>


    <element name="DataSet">
    	<complexType>
    		<sequence>
    			<element name="Data" type="tns:Data" maxOccurs="unbounded" minOccurs="0"></element>
    		</sequence>
    	</complexType>
    </element>
</schema>

=== ElAmriMehdi/Test-avec-Junit4/Tp2/donneesDeTests.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:DataSet xmlns:tns="http://www.example.org/RationnelSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/RationnelSchema RationnelSchema.xsd ">
  <tns:Data>
  
    <tns:r1 denominateur="3" numerateur="2"/>
    <tns:r2 denominateur="3" numerateur="4"/>
    <tns:resultAddition denominateur="1" numerateur="2"/>
    <tns:resultSoustraction denominateur="3" numerateur="-2"/>
    
  </tns:Data>
 
  <tns:Data>
  
    <tns:r1 denominateur="9" numerateur="2"/>
    <tns:r2 denominateur="3" numerateur="1"/>
    <tns:resultAddition denominateur="9" numerateur="5"/>
    <tns:resultSoustraction denominateur="9" numerateur="-1"/>
    
  </tns:Data>
  
  
</tns:DataSet>
